trend_analysis_task:
  description: >
    Analyze the cleaned LinkedIn posts:
        - Identify user's writing style.
        - Detect the user's personal touch.
        - Understand the user's targeted audience.
        - Identify user's linkedin post length on average.
        - Paragraphing and formatting for LinkedIn.
        from
         "{activities}"
                              
  expected_output: >
    JSON structure containing theme, writing style and interests of user. from {activities}
  agent: trend_analysis_agent


post_generation_task:
  description: >
    Generate **One highly personalized LinkedIn post** based solely on the following dynamic inputs and the provided content theme.

                🔹 **Dynamic Inputs:**
                - **Writing Style:** The user prefers the post to be written in the style of **"{writing_style}"**.
                - **Personal Touch:** Incorporate a personal touch that reflects the user's unique perspective: **"{personal_touch}"**.
                - **Target Audience:** The post should be tailored to **"{target_audience}"**.
                - **Post content length:** The average post length is **"{post_length}"**.
                - **User's Paragraphing and formatting:** The post should be properly paragraphed and formatted like **"{paragraph}"**.
                - **Content Idea:** The content theme will be provided in **"{static_linkedin_post}"**.

                🔹 **Content Guidelines:**
                - The post must not contain any emojis.
                - The post must include **#HiDevs** as a hashtag along with other relevant hashtags.
                - The post should be written in English.
                - **The post must be engaging and relevant**, focusing on the provided content idea without any additional constraints.

  
  expected_output: >
    1 LinkedIn-ready post formatted for engagement according to the user's preferences.
  agent: post_generation_agent



post_enhancement_task:
  description: >
    Please incorporate the following feedback if present: 
    {feedback}
    Enhance the provided post content while strictly adhering to:
    - Exact length requirement: {length} words
    - Mandatory keyword inclusion: {keywords}
    - Consistent {tone} tone throughout
    - Preservation of core message from original post
    - The post must include **#HiDevs** as a hashtag along with other relevant hashtags.
    Original Content:
    {post}
    
    Rules:
    - Never change the fundamental argument/point
    - Inject keywords naturally, never force them
    - Adjust length by expanding/compressing examples, not cutting core ideas
  expected_output: >
    A single enhanced LinkedIn post meeting all specified requirements,
    returned as JSON with post_heading and post_content fields
  agent: linkedin_post_enhancer


post_validation_task:
  description: >
    Rigorously validate the enhanced post against these criteria:
    - Exact word count: {length} (±5% tolerance)
    - All keywords present: {keywords}
    - Tone consistency: {tone}
    - Readability score > 70
    - Core message preservation
    - Formatting: Proper paragraphing and structure for LinkedIn
    - No spelling or grammatical errors
    - No emojis or informal language
    - The post must include **#HiDevs** as a hashtag along with other relevant hashtags.
    
    Linkedin Post to verify :
    {post}
  expected_output: >
    JSON structure with validation results:
    {
      "valid": boolean,
      "feedback": "Detailed improvement suggestions"
    }
  agent: post_validator

